name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Goodbye World Test
      id: goodbye-world-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Goodbye World Test
        setup-command: ''
        command: cat goodbye.txt
        input: ''
        expected-output: Goodbye, World!
        comparison-method: exact
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GOODBYE-WORLD-TEST_RESULTS: "${{steps.goodbye-world-test.outputs.result}}"
      with:
        runners: goodbye-world-test
